### ISSUE TITLE
Error when running with a recently build csproj

### ISSUE THREAD

**Issue by jakenuts** [lietho/dotnet-dependency-graph#16]
`dependency-graph "X:\DealerVision\FieldService\DealerVision.FieldService.Web\DealerVision.FieldService.Web.csproj"`

```
Unhandled exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at DependencyGraph.Core.Graph.Factory.DependencyGraphFactory.AddProjectToGraph(DependencyGraph graph, LockFile lockFile, String[] includes, String[] excludes, Nullable`1 maxDepth) in C:\dev\dotnet-dependency-graph\src\DependencyGraph.Core\Graph\Factory\DependencyGraphFactory.cs:line 32
   at DependencyGraph.Core.Graph.Factory.DependencyGraphFactory.FromLockFile(LockFile lockFile, String[] includes, String[] excludes, Nullable`1 maxDepth) in C:\dev\dotnet-dependency-graph\src\DependencyGraph.Core\Graph\Factory\DependencyGraphFactory.cs:line 19
   at DependencyGraph.App.Commands.DependencyGraphRootCommand.HandleCommand(FileInfo projectFile, VisualizerType visualizerType, FileInfo outputFile, String[] includes, String[] excludes, Nullable`1 maxDepth, Nullable`1 noRestore) in C:\dev\dotnet-dependency-graph\src\DependencyGraph.App\Commands\DependencyGraphRootCommand.cs:line 102
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DependencyGraph.App.Application.<>c.<<RunAsync>b__2_0>d.MoveNext() in C:\dev\dotnet-dependency-graph\src\DependencyGraph.App\Application.cs:line 28
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

[DealerVision.FieldService.Web.deps.json](https://github.com/user-attachments/files/16821015/DealerVision.FieldService.Web.deps.json)

**Comment by lietho** [comment]
Hi,

would it be possible that you also provide the `project.assets.json`-File located in the `obj` folder of your project?
